### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by schrammalama** [TheNathannator/WiitarThing#13]
I'll start by saying that I don't have HID Wiimote installed or any other Wii Remote software other the Wiitarthing.
When I press the sync button I get this error.

The application has encountered an unhandled error and crashed
Provide value on 'System.Windows.Baml2006.TypeConverterMarkup...
 at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at WiitarThing.Windows.SyncWindow.InitializeComponent() in C:\Users\natha\source\repos\WiitarThing\WiitarThing\Windows\SyncWindow.xaml:line 1
   at WiitarThing.Windows.SyncWindow..ctor() in C:\Users\natha\source\repos\WiitarThing\WiitarThing\Windows\SyncWindow.xaml.cs:line 27
   at WiitarThing.MainWindow.btnSync_Click(Object sender, RoutedEventArgs e) in C:\Users\natha\source\repos\WiitarThing\WiitarThing\Windows\MainWindow.xaml.cs:line 433
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at WiitarThing.App.Main() in C:\Users\natha\source\repos\WiitarThing\WiitarThing\App.xaml.cs:line 27

**Comment by TheNathannator** [comment]
I thought I fixed this issue lol, though the last time this was reported it was on program startup. Might need to apply the same fix somewhere in the sync menu as well.

Can you open up Windows settings and search for `color profile`, then open Color Management and take a screenshot of the Advanced tab? Should look like this:

![image](https://github.com/TheNathannator/WiitarThing/assets/29052821/de90f42f-f419-47ae-b955-7d1cb011f1bd)

The `Device profile` setting needs to be set to `sRGB IEC61966-2.1`, as is the default for me here. Your system's default is most likely different, which is tripping up WiitarThing due to a bug in the framework it uses.

**Comment by schrammalama** [comment]
that fixed it thank you

**Comment by TheNathannator** [comment]
Awesome! This is definitely the same issue I was thinking of then, I'll take a look and see what I can do.
